version: '3.1'

services:

  db:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=hibernate_db
      - MYSQL_USER=ramiro
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=mysql
    container_name: mysqldb
